### ISSUE TITLE
System.IO.IOException: unknown tag 23 encountered When use ApnSender

### ISSUE THREAD

**Issue by neiesc** [andrei-m-code/net-core-push-notifications#32]
It works in version after v3.

<details>
System.IO.IOException: unknown tag 23 encountered
   at Org.BouncyCastle.Asn1.Asn1InputStream.BuildObject(Int32 tag, Int32 tagNo, Int32 length) in /_/crypto/src/asn1/Asn1InputStream.cs:line 129
   at Org.BouncyCastle.Asn1.Asn1InputStream.ReadObject() in /_/crypto/src/asn1/Asn1InputStream.cs:line 224
   at Org.BouncyCastle.Asn1.Asn1Object.FromByteArray(Byte[] data) in /_/crypto/src/asn1/Asn1Object.cs:line 22
   at Org.BouncyCastle.Security.PrivateKeyFactory.CreateKey(Byte[] privateKeyInfoData) in /_/crypto/src/security/PrivateKeyFactory.cs:line 33
   at CorePush.Apple.ApnSender.GetEllipticCurveAlgorithm(String privateKey) in C:\Dev\CorePush\net-core-push-notifications\CorePush\Apple\ApnSender.cs:line 127
   at CorePush.Apple.ApnSender.CreateJwtToken() in C:\Dev\CorePush\net-core-push-notifications\CorePush\Apple\ApnSender.cs:line 111
   at CorePush.Apple.ApnSender.<GetJwtToken>b__8_0(String _) in C:\Dev\CorePush\net-core-push-notifications\CorePush\Apple\ApnSender.cs:line 93
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at CorePush.Apple.ApnSender.GetJwtToken() in C:\Dev\CorePush\net-core-push-notifications\CorePush\Apple\ApnSender.cs:line 93
   at CorePush.Apple.ApnSender.SendAsync(Object notification, String deviceToken, String apnsId, Int32 apnsExpiration, Int32 apnsPriority, Boolean isBackground) in C:\Dev\CorePush\net-core-push-notifications\CorePush\Apple\ApnSender.cs:line 67
</details>

**Comment by andrei-m-code** [comment]
This would be latest. I just got that issue running push notification service on docker image `mcr.microsoft.com/azure-functions/dotnet:3.0`. I'll need to figure it out sooner or later... Any help would be appreciated.

**Comment by neiesc** [comment]
Tomorrow I'll analazy more thanks.

**Comment by neiesc** [comment]
I double-check and I pass P8PrivateKey invalid sorry.
