### ISSUE TITLE
Firebase CryptographicException when deployed to production server

### ISSUE THREAD

**Issue by danielgindi** [andrei-m-code/net-core-push-notifications#88]
This works correctly locally. But when deployed - I received `CryptographicException` "The system cannot find the file specified.".

```
at System.Security.Cryptography.CngKey.Import(ReadOnlySpan`1 keyBlob, String curveName, CngKeyBlobFormat format, CngProvider provider)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.RSACng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.PemKeyHelpers.ImportPem(ReadOnlySpan`1 input, FindImportActionFunc callback)
   at CorePush.Firebase.FirebaseSender.GetMasterToken()
   at CorePush.Firebase.FirebaseSender.GetJwtTokenAsync()
   at CorePush.Firebase.FirebaseSender.SendAsync(Object payload, CancellationToken cancellationToken)
```

Seems like `RSACryptoServiceProvider` should be used instead.

**Comment by Itsey** [comment]
I have this issue too, on an app service plan in Azure - did you find a workaround / fix or alternative?

**Comment by danielgindi** [comment]
> Have you guys tried to do this?
> 
> https://github.com/andrei-m-code/net-core-push-notifications?tab=readme-ov-file#azure-functions-and-azure-app-service

You do not always want to (or can) load the user profile.
A different approach that would solve this is decoding the base64 in the pem file, and initializing it with EphemeralKeySet.

I could make a PR.

**Comment by danielgindi** [comment]
Well, apparently you are already using BouncyCastle, so I made a PR to use that.

**Comment by danielgindi** [comment]
> Excellent work. Thank you! Merged. Tested. Pushed to nuget.


Thank you!

I believe I'll make another PR, that will avoid re-importing the PEM for every message. This bothered me in the old configuration as well.
See you soon ;-)
